---
- name:
  hosts: all
  tasks:
  # 1) 방화벽 해제 - http, https
  # 2) 서비스 설정 파일 삭제 - /var/www/html/index.html
  # 3) 서비스 정지 - httpd, firewalld
  # 4) 패키지 삭제 - httpd, mod_ssl, firewalld

  # 1) 방화벽 해제 - http, https
    - name: 방화벽 해제 - http, https
      firewalld:
        service: "{{ item }}"
        state: disabled
        immediate: yes
      loop:
        - http
        - https
  # 2) 서비스 설정 파일 삭제 - /var/www/html/index.html
    - name: 서비스 설정 파일 삭제 - /var/www/html/index.html
      file:
        path: /var/www/html/index.html
        state: absent
  # 3) 서비스 정지 - httpd, firewalld
    - name: 서비스 정지 - httpd, firewalld
      service:
        name: "{{ item }}"
        state: stopped
      loop:
        - httpd
        - firewalld
  # 4) 패키지 삭제 - httpd, mod_ssl, firewalld
    - name: 패키지 삭제 - httpd, mod_ssl, firewalld
      yum:
        name:
          - httpd
          - mod_ssl
          - firewalld
        state: absent
