---
- name: 웹 서버 설정
  hosts: webserver
  tasks:
  # 1) 웹 패키지 설치
  # 2) 웹 패키지 기동

  # 1) 웹 패키지 설치
    - name:
      yum:
        name: "{{ ansible_local.custom.general.package }}"
        state: present
  # 2) 웹 패키지 기동
    - name:
      service:
        name: "{{ ansible_local.custom.general.service }}"
        state: "{{ ansible_local.custom.general.state }}"
        enabled: yes