---
- name:
  hosts: fileservers
  tasks:
    - name: 변수 포함시키기
      include_vars: package.yml
    - name: Install the package - epel-release
      include_tasks: install_package.yml
      vars:
        packages:
          web_pkg: epel-release
    - name: Install the package - tomcat
      include_tasks: install_package.yml
      vars:
        packages:
          web_pkg: tomcat
