---
- name: Restore playbook.yml
  hosts: all
  vars_files: paths.yml
  tasks:
    # 1) Delete Directory - paths.yml
    # 2) Delete Package - httpd, tomcat
    
    # 1) Delete Directory - paths.yml
    - name: Delete Directory
      file:
        path: "{{ item }}"
        state: absent
      with_items: 
        - "{{ paths.fileserver }}"
        - "{{ paths.dbpath }}"
    # 2) Delete Package  - httpd, tomcat
    - name: Delete Package
      yum:
        name:
          - httpd
          - tomcat
        state: absent