---
- name: Configure /etc/motd
  hosts: all
  gather_facts: true
  vars:
    - system_owner: webmaster@example.com
  tasks:
    - name:
      template:
        src: template/motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'