---
# tasks file for git
- name: Load the OS specific variables
  tags: git
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install the packages in Redhat derivates
  tags: git
  yum: name={{ item }} state=present
  with_items: '{{ git_pkgs }}'
  when: ansible_os_family == 'RedHat'

- name: Install the packages in Debian derivates
  tags: git
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=600
  with_items: '{{ git_pkgs }}'
  when: ansible_os_family == 'Debian'

