---
- name: lamp 설정
  hosts: lamp
  tasks:
    - name: 변수 포함시키기
      include_vars: vars/main.yml
    - name: task 포함시키기
      include_tasks: tasks/main.yml
    - name: 최신 버전 firewalld 패키지 설치
      yum:
        name: firewalld
        state: latest
    - name: 방화벽 서비스 기동
      service:
        name: firewalld
        state: started
        enabled: yes
      loop:
    - name: /var/www/hyml/index.html 셍성
      copy:
        content: "{{ ansible_fqdn }}({{ ansible_default_ipv4.address }}) has been customized by Ansible.\n" 
        dest: "{{ web_root }}/index.html"

  