---
- name: Restore playbook.yml
  hosts: web1
  tasks:
    # 1) 방화벽 닫기 - http
    # 2) 서비스 내리기 - firewalld, httpd, mariadb
    # 3) 웹 서비스 설정 삭제
    # * /var/www/html/index.html
    # 4) 패키지 삭제 - httpd, firewalld, mariadb-server
    # 5) 팩트 삭제 - /etc/ansible/facts.d/

    # 1) 방화벽 닫기 - http, https
    - name:
      firewalld:
        service: "{{ item }}"
        state: disabled
      loop:
        - http
        - https
    # 2) 서비스 내리기 - firewalld, httpd, mariadb
    - name:
      service:
        name: "{{ item }}"
        state: stopped
      loop:
        - firewalld
        - httpd
        - mariadb
    # 3) 웹 서비스 설정 삭제
    - name:
      file:
        path: /var/www/html/index.html
        state: absent
    # * /var/www/html/index.html
    # 4) 패키지 삭제 - httpd, firewalld, mariadb-server
    - name:
      yum:
        name:
          - httpd
          - firewalld
          - mariadb-server
        state: absent
    # 5) 팩트 삭제 - /etc/ansible/facts.d/
    - name:
      file:
        path: /etc/ansible/facts.d/
        state: absent