---
- name: Use the fetch module to retrieve secure logfiles
  hosts: all
  tasks:
    - name: Fetch the /var/log/secure log file from managed hosts
      fetch:
        src: /var/log/secure
        dest: "secure-backup/{{ inventory_hostname }}-securelog"
        flat: yes