---
- name:
  hosts:
  vars_files: vars.yml
  tasks:
    - name: Show Failed System Requirements Message
      file:
        msg: "The {{ inventory_hostname }} did not meet minimum reqs."
      when: >
        ansible_memtotal_mb < min_ram_mb or
        ansible_distribution != "CentOS"

    - name: Ensure required packages are present
      yum:
        name: "{{ packages }}"
        state: latest
    - name: Ensure services are started and enabled
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: "{{ services }}"
    - name: Setting up the SSL cert directory and config files
      block:
        - name: Create SSL cert directory
          file:
            path: "{{ ssl_cert_dir }}"
            state: directory
        - name: Copy Config files
          copy:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
          loop: "{{ web_config_files }}"
          notify: restart web service
      rescue:
        name: Configuration Error Message
        debug:
          msg: >
            One or more of the Configuration
            changes faild, but the web service is still active
    - name: Ensure web server ports are open
      firewald:
        service: "{{ item }}"
        immediate: true
        permanent: true
        state: enabled
      loop:
        - httpd
        - https
  handlers:
    - name: restart web service
      service:
        name: "{{ web_service }}"
        state: restarted
      



