---
- name: DB 기동하기
  hosts: database_prod
  vars:
    mariadb_packages:
      - mariadb-server
      - python3-PyMySQL
    mariadb_service: mariadb
  tasks:
    - name: DB 패키지 설치 - mariadb-server, python3-PyMySQL
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ mariadb_packages }}"
      when: ansible_distribution == 'CentOS'
    - name: DB 서비스 기동
      service:
        name: "{{ mariadb_service }}"
        state: started
        enabled: yes
