---
- name:
  hosts: all
  vars:
    mariadb_packages:
      - mariadb-server
      - python3-PyMySQL
    mariadb_service: mariadb
  tasks:
    - name:
      service:
        name: "{{ mariadb_service }}"
        state: stopped
    - name:
      yum:
        name: "{{ item }}"
        state: absent
      with_items: "{{ mariadb_packages }}"